import type { Metadata } from "next";
import "./globals.css";
import { ProductProvider } from '@/context/ProductContext'
import { AuthProvider } from '@/context/AuthContext';
import { CartProvider } from '@/context/CartContext';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ProductProvider>
            <CartProvider>
              {children}
            </CartProvider>
          </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
